/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedComunidadesRouteImport } from './routes/_authenticated/comunidades'
import { Route as AuthenticatedEstabelecimentosRouteImport } from './routes/_authenticated/estabelecimentos'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLocalRouteImport } from './routes/_authenticated/local'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedComunidadeSlugRouteImport } from './routes/_authenticated/comunidade.$slug'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedConfiguracoesContatoRouteImport } from './routes/_authenticated/configuracoes.contato'
import { Route as AuthenticatedConfiguracoesPrivacidadeRouteImport } from './routes/_authenticated/configuracoes.privacidade'
import { Route as AuthenticatedConfiguracoesPrivacidadePoliticaRouteImport } from './routes/_authenticated/configuracoes.privacidade-politica'
import { Route as AuthenticatedConfiguracoesTermosRouteImport } from './routes/_authenticated/configuracoes.termos'
import { Route as AuthenticatedEstabelecimentoIdRouteImport } from './routes/_authenticated/estabelecimento.$id'
import { Route as AuthenticatedPetPetIdRouteImport } from './routes/_authenticated/pet.$petId'
import { Route as AuthenticatedPetNovoRouteImport } from './routes/_authenticated/pet.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComunidadesRoute =
  AuthenticatedComunidadesRouteImport.update({
    id: '/comunidades',
    path: '/comunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstabelecimentosRoute =
  AuthenticatedEstabelecimentosRouteImport.update({
    id: '/estabelecimentos',
    path: '/estabelecimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocalRoute = AuthenticatedLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadeSlugRoute =
  AuthenticatedComunidadeSlugRouteImport.update({
    id: '/comunidade/$slug',
    path: '/comunidade/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesContatoRoute =
  AuthenticatedConfiguracoesContatoRouteImport.update({
    id: '/configuracoes/contato',
    path: '/configuracoes/contato',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesPrivacidadeRoute =
  AuthenticatedConfiguracoesPrivacidadeRouteImport.update({
    id: '/configuracoes/privacidade',
    path: '/configuracoes/privacidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesPrivacidadePoliticaRoute =
  AuthenticatedConfiguracoesPrivacidadePoliticaRouteImport.update({
    id: '/configuracoes/privacidade-politica',
    path: '/configuracoes/privacidade-politica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesTermosRoute =
  AuthenticatedConfiguracoesTermosRouteImport.update({
    id: '/configuracoes/termos',
    path: '/configuracoes/termos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstabelecimentoIdRoute =
  AuthenticatedEstabelecimentoIdRouteImport.update({
    id: '/estabelecimento/$id',
    path: '/estabelecimento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetPetIdRoute = AuthenticatedPetPetIdRouteImport.update({
  id: '/pet/$petId',
  path: '/pet/$petId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetNovoRoute = AuthenticatedPetNovoRouteImport.update({
  id: '/pet/novo',
  path: '/pet/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidades': typeof AuthenticatedComunidadesRoute
  '/estabelecimentos': typeof AuthenticatedEstabelecimentosRoute
  '/home': typeof AuthenticatedHomeRoute
  '/local': typeof AuthenticatedLocalRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/social': typeof AuthenticatedSocialRoute
  '/comunidade/$slug': typeof AuthenticatedComunidadeSlugRoute
  '/configuracoes/contato': typeof AuthenticatedConfiguracoesContatoRoute
  '/configuracoes/privacidade': typeof AuthenticatedConfiguracoesPrivacidadeRoute
  '/configuracoes/privacidade-politica': typeof AuthenticatedConfiguracoesPrivacidadePoliticaRoute
  '/configuracoes/termos': typeof AuthenticatedConfiguracoesTermosRoute
  '/estabelecimento/$id': typeof AuthenticatedEstabelecimentoIdRoute
  '/pet/$petId': typeof AuthenticatedPetPetIdRoute
  '/pet/novo': typeof AuthenticatedPetNovoRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidades': typeof AuthenticatedComunidadesRoute
  '/estabelecimentos': typeof AuthenticatedEstabelecimentosRoute
  '/home': typeof AuthenticatedHomeRoute
  '/local': typeof AuthenticatedLocalRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/social': typeof AuthenticatedSocialRoute
  '/comunidade/$slug': typeof AuthenticatedComunidadeSlugRoute
  '/configuracoes/contato': typeof AuthenticatedConfiguracoesContatoRoute
  '/configuracoes/privacidade': typeof AuthenticatedConfiguracoesPrivacidadeRoute
  '/configuracoes/privacidade-politica': typeof AuthenticatedConfiguracoesPrivacidadePoliticaRoute
  '/configuracoes/termos': typeof AuthenticatedConfiguracoesTermosRoute
  '/estabelecimento/$id': typeof AuthenticatedEstabelecimentoIdRoute
  '/pet/$petId': typeof AuthenticatedPetPetIdRoute
  '/pet/novo': typeof AuthenticatedPetNovoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/comunidades': typeof AuthenticatedComunidadesRoute
  '/_authenticated/estabelecimentos': typeof AuthenticatedEstabelecimentosRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/local': typeof AuthenticatedLocalRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/comunidade/$slug': typeof AuthenticatedComunidadeSlugRoute
  '/_authenticated/configuracoes/contato': typeof AuthenticatedConfiguracoesContatoRoute
  '/_authenticated/configuracoes/privacidade': typeof AuthenticatedConfiguracoesPrivacidadeRoute
  '/_authenticated/configuracoes/privacidade-politica': typeof AuthenticatedConfiguracoesPrivacidadePoliticaRoute
  '/_authenticated/configuracoes/termos': typeof AuthenticatedConfiguracoesTermosRoute
  '/_authenticated/estabelecimento/$id': typeof AuthenticatedEstabelecimentoIdRoute
  '/_authenticated/pet/$petId': typeof AuthenticatedPetPetIdRoute
  '/_authenticated/pet/novo': typeof AuthenticatedPetNovoRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comunidades'
    | '/estabelecimentos'
    | '/home'
    | '/local'
    | '/perfil'
    | '/servicos'
    | '/social'
    | '/comunidade/$slug'
    | '/configuracoes/contato'
    | '/configuracoes/privacidade'
    | '/configuracoes/privacidade-politica'
    | '/configuracoes/termos'
    | '/estabelecimento/$id'
    | '/pet/$petId'
    | '/pet/novo'
    | '/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comunidades'
    | '/estabelecimentos'
    | '/home'
    | '/local'
    | '/perfil'
    | '/servicos'
    | '/social'
    | '/comunidade/$slug'
    | '/configuracoes/contato'
    | '/configuracoes/privacidade'
    | '/configuracoes/privacidade-politica'
    | '/configuracoes/termos'
    | '/estabelecimento/$id'
    | '/pet/$petId'
    | '/pet/novo'
    | '/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/comunidades'
    | '/_authenticated/estabelecimentos'
    | '/_authenticated/home'
    | '/_authenticated/local'
    | '/_authenticated/perfil'
    | '/_authenticated/servicos'
    | '/_authenticated/social'
    | '/_authenticated/comunidade/$slug'
    | '/_authenticated/configuracoes/contato'
    | '/_authenticated/configuracoes/privacidade'
    | '/_authenticated/configuracoes/privacidade-politica'
    | '/_authenticated/configuracoes/termos'
    | '/_authenticated/estabelecimento/$id'
    | '/_authenticated/pet/$petId'
    | '/_authenticated/pet/novo'
    | '/_authenticated/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comunidades': {
      id: '/_authenticated/comunidades'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof AuthenticatedComunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estabelecimentos': {
      id: '/_authenticated/estabelecimentos'
      path: '/estabelecimentos'
      fullPath: '/estabelecimentos'
      preLoaderRoute: typeof AuthenticatedEstabelecimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/local': {
      id: '/_authenticated/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof AuthenticatedLocalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidade/$slug': {
      id: '/_authenticated/comunidade/$slug'
      path: '/comunidade/$slug'
      fullPath: '/comunidade/$slug'
      preLoaderRoute: typeof AuthenticatedComunidadeSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/contato': {
      id: '/_authenticated/configuracoes/contato'
      path: '/configuracoes/contato'
      fullPath: '/configuracoes/contato'
      preLoaderRoute: typeof AuthenticatedConfiguracoesContatoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/privacidade': {
      id: '/_authenticated/configuracoes/privacidade'
      path: '/configuracoes/privacidade'
      fullPath: '/configuracoes/privacidade'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPrivacidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/privacidade-politica': {
      id: '/_authenticated/configuracoes/privacidade-politica'
      path: '/configuracoes/privacidade-politica'
      fullPath: '/configuracoes/privacidade-politica'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPrivacidadePoliticaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/termos': {
      id: '/_authenticated/configuracoes/termos'
      path: '/configuracoes/termos'
      fullPath: '/configuracoes/termos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesTermosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estabelecimento/$id': {
      id: '/_authenticated/estabelecimento/$id'
      path: '/estabelecimento/$id'
      fullPath: '/estabelecimento/$id'
      preLoaderRoute: typeof AuthenticatedEstabelecimentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pet/$petId': {
      id: '/_authenticated/pet/$petId'
      path: '/pet/$petId'
      fullPath: '/pet/$petId'
      preLoaderRoute: typeof AuthenticatedPetPetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pet/novo': {
      id: '/_authenticated/pet/novo'
      path: '/pet/novo'
      fullPath: '/pet/novo'
      preLoaderRoute: typeof AuthenticatedPetNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComunidadesRoute: typeof AuthenticatedComunidadesRoute
  AuthenticatedEstabelecimentosRoute: typeof AuthenticatedEstabelecimentosRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLocalRoute: typeof AuthenticatedLocalRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedComunidadeSlugRoute: typeof AuthenticatedComunidadeSlugRoute
  AuthenticatedConfiguracoesContatoRoute: typeof AuthenticatedConfiguracoesContatoRoute
  AuthenticatedConfiguracoesPrivacidadeRoute: typeof AuthenticatedConfiguracoesPrivacidadeRoute
  AuthenticatedConfiguracoesPrivacidadePoliticaRoute: typeof AuthenticatedConfiguracoesPrivacidadePoliticaRoute
  AuthenticatedConfiguracoesTermosRoute: typeof AuthenticatedConfiguracoesTermosRoute
  AuthenticatedEstabelecimentoIdRoute: typeof AuthenticatedEstabelecimentoIdRoute
  AuthenticatedPetPetIdRoute: typeof AuthenticatedPetPetIdRoute
  AuthenticatedPetNovoRoute: typeof AuthenticatedPetNovoRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComunidadesRoute: AuthenticatedComunidadesRoute,
  AuthenticatedEstabelecimentosRoute: AuthenticatedEstabelecimentosRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLocalRoute: AuthenticatedLocalRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedComunidadeSlugRoute: AuthenticatedComunidadeSlugRoute,
  AuthenticatedConfiguracoesContatoRoute:
    AuthenticatedConfiguracoesContatoRoute,
  AuthenticatedConfiguracoesPrivacidadeRoute:
    AuthenticatedConfiguracoesPrivacidadeRoute,
  AuthenticatedConfiguracoesPrivacidadePoliticaRoute:
    AuthenticatedConfiguracoesPrivacidadePoliticaRoute,
  AuthenticatedConfiguracoesTermosRoute: AuthenticatedConfiguracoesTermosRoute,
  AuthenticatedEstabelecimentoIdRoute: AuthenticatedEstabelecimentoIdRoute,
  AuthenticatedPetPetIdRoute: AuthenticatedPetPetIdRoute,
  AuthenticatedPetNovoRoute: AuthenticatedPetNovoRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
